version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: testapp
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  angular:
    build:
      context: AngularDocker # Use an image built from the specified dockerfile in the `angular-11-social-login` directory.
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://127.0.0.1:8081/
    ports:
      - "4200:80" # Map the exposed port 80 on the container to port 4200 on the host machine
    restart: always
    #depends_on:
      #- app-server
    networks:
      - frontendNetwork


volumes:
  mysql-data:
  
networks:
  backendNetwork:
  frontendNetwork:
